version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      golang-dependencies:
        # for now we only do this for version updates
        # "security-updates" are still done one by one
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
                      # ecosystem. Note: using "*" may open a large pull request

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      npm-dependencies:
        # for now we only do this for version updates
        # "security-updates" are still done one by one
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
                      # ecosystem. Note: using "*" may open a large pull request
