name: CI python-server

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'python-server/**'
      - 'config/**'
      - 'cmd/eval_hub/**'
      - 'cmd/eval_runtime_sidecar/**'
      - 'internal/**'
      - 'pkg/**'
      - 'Makefile'
      - '.github/workflows/ci-python-server.yml'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  test-server-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Set up uv python
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: '3.11'
      - name: Build server binary for this platform via cross-compile target
        run: make cross-compile
      - name: Build sidecar binary for this platform via cross-compile target
        run: make cross-compile-sidecar
      - name: Build wheel
        run: make build-wheel
      - name: Install wheel
        run: |
          uv venv --python 3.11 .venv
          uv pip install --python .venv python-server/dist/*.whl
      - name: Wheel sanity test
        run: |
          source .venv/bin/activate
          chmod +x scripts/gha_wheel_sanity_test.sh
          ./scripts/gha_wheel_sanity_test.sh
