name: CI python-server

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'python-server/**'
      - 'config/**'
      - 'cmd/eval_hub/**'
      - 'internal/**'
      - 'pkg/**'
      - 'Makefile'
      - '.github/workflows/ci-python-server.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"
      - name: Set up uv python
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: '3.11'
      - name: Build binary for this platform via cross-compile target
        run: make cross-compile
      - name: Copy binary to python-server manually (this is done usually by .github/workflows/publish-python-server.yml)
        run: |
          mkdir -p python-server/evalhub_server/binaries/
          cp bin/eval-hub-* python-server/evalhub_server/binaries/
          chmod +x python-server/evalhub_server/binaries/*
      - name: Build wheel and run tests
        run: make build-wheel test-python-server
