name: Sync branch incubation
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    if: ${{ github.repository == 'opendatahub-io/eval-hub' }}
    runs-on: ubuntu-latest
    name: Syncing branch incubation
    steps:
      - name: Checkout
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@ea58ab6e406fd3ad016a064b31270bbb41127f41 # 1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "incubation"
      - name: Add labels
        if: ${{ steps.pull.outputs.PULL_REQUEST_NUMBER != '' }}
        uses: actions/github-script@d746ffe35508b1917358783b479e04febd2b8f71 # v9.0.0
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{steps.pull.outputs.PULL_REQUEST_NUMBER}},
              labels: ['bot/sync-incubation', 'tide/merge-method-merge']
            });